import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-[#0d1224] dark:text-[rgb(var(--foreground-rgb))] bg-white antialiased text-black`}
      >
        <Navbar />
        <main className="min-h-screen relative mx-auto text-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
