import type { Metadata } from "next";

import Footer from "@/components/ui/footer";
import Navbar from "@/components/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="min-h-screen relative mx-auto text-white">
        {children}
      </main>
      <Footer />
    </>
  );
}
